# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66de3d3300636ff6a225bef1d8bb3c1d529dd43b682dc572130372637cac2c93026ccadf0be9bf2caea2909f89e4a6e593466429f4bc55f4add666d044d595c0

test:
  secret_key_base: e54e297b592ea2ddc3b229aaf7a400e6ca93bd425056a2a5497c6b77b0a5add8c2d9cebc8aae8552b468948602eeadbebe729c6aa7a3f9ad5b3fa7a39c2259d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
